### =========================================
### AULA 5: ROTAS DE DIAGNÓSTICO
### =========================================

### Testar integridade do sistema (Health Check)
GET http://localhost:3000/api/health

### Testar versão da aplicação

GET http://localhost:3000/api/version

### Listar todas as tarefas (GET)
GET http://localhost:3000/api/tasks

### Criar nova tarefa (POST)

POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Estudar matemática"
}

### Deletar tarefa (DELETE)
DELETE http://localhost:3000/api/tasks/1786580785990